name: DawPaper
version: '${project.version}'
main: fr.daweii.dawpaper.Main
api-version: 1.20
authors: [ Daweii ]
commands:
  openinv:
    description: sdfghj
  say:
    description: sdfghj
  staff:
    description: xcvbhj
  vanish:
    description: zerfgfezfdsfd
  commandetest:
    description: drtyuhbvcft
  ping:
    description: dftyhbvcfgty
  spawn:
    description: dfgferfds
  cuntest:
    description: efdfddg
  item:
    description: sdrtgvcdrtyhgvfdrt
  moneygive:
    description: dsfsdffds
    aliases: givemoney
  test:
    description: cdrtyhjnbvghjnbghn h